from __future__ import annotations

"""Curated fact deck used by the optimization progress overlay."""

TRAIN_FACTS: tuple[str, ...] = (
    "Lokomotywa Rocket zwyciężyła w próbach Rainhill w 1829 roku.",
    "Pierwsza linia londyńskiego metra ruszyła w 1863 roku i używała parowozów.",
    "Najpowszechniejszy rozstaw szyn na świecie wynosi 1435 mm.",
    "Lokomotywa spalinowo-elektryczna napędza koła silnikami elektrycznymi zasilanymi przez generator.",
    "Shinkansen rozpoczął regularne kursy między Tokio i Osaką w 1964 roku.",
    "Francuski TGV ustanowił w 2007 roku rekord 574,8 km/h dla pociągu na kołach.",
    "Maglev może poruszać się bez kontaktu kół z szyną dzięki siłom magnetycznym.",
    "Stożkowy profil kół pomaga zestawowi kołowemu samoczynnie ustawiać się na torze.",
    "Obrzeże koła kolejowego jest zabezpieczeniem prowadzącym, ale zwykle nie powinno stale trzeć o szynę.",
    "Podkłady rozkładają obciążenie szyn na podsypkę i utrzymują właściwy rozstaw toru.",
    "Podsypka tłuczniowa stabilizuje tor i ułatwia odprowadzanie wody.",
    "Szyna bezstykowa ogranicza stuk na łączeniach, lecz wymaga kontroli naprężeń cieplnych.",
    "Pantograf utrzymuje ślizgowy kontakt pojazdu z przewodem jezdnym.",
    "Sieć trakcyjna jest prowadzona zygzakiem, aby zużycie nakładki pantografu było równomierne.",
    "Wózki kolejowe obracają się względem pudła i ułatwiają przejazd przez łuki.",
    "Pociąg z wychylnym pudłem zmniejsza odczuwane przyspieszenie boczne na łuku.",
    "Samoczynny hamulec pneumatyczny uruchamia się również przy utracie ciśnienia w przewodzie głównym.",
    "George Westinghouse opatentował swój hamulec pneumatyczny w 1869 roku.",
    "Hamowanie rekuperacyjne może oddawać energię do sieci lub wykorzystywać ją w innym pojeździe.",
    "Droga hamowania ciężkiego pociągu towarowego może przekraczać kilometr.",
    "Odcinki blokowe pomagają zachować bezpieczny odstęp między pociągami.",
    "Obwód torowy wykrywa pociąg dzięki zwarciu obu szyn przez zestawy kołowe.",
    "Licznik osi potwierdza zwolnienie odcinka, porównując liczbę osi wjeżdżających i wyjeżdżających.",
    "ETCS może przekazywać maszyniście ograniczenia i pozwolenie na jazdę bezpośrednio do kabiny.",
    "Semafor kształtowy przekazuje sygnał położeniem ruchomego ramienia.",
    "Kolej zębata używa dodatkowej zębatki, aby pokonywać nachylenia zbyt strome dla zwykłej adhezji.",
    "Kolej linowo-terenowa zwykle równoważy masę dwóch wagonów połączonych liną.",
    "Linia Transsyberyjska łączy Moskwę z Władywostokiem na trasie liczącej ponad dziewięć tysięcy kilometrów.",
    "Tunel pod kanałem La Manche został otwarty dla regularnego ruchu w 1994 roku.",
    "Na granicy różnych rozstawów toru stosuje się wymianę wózków albo zestawy o zmiennym rozstawie kół.",
    "Górka rozrządowa wykorzystuje grawitację do kierowania wagonów na odpowiednie tory.",
    "Podwójne piętrowanie kontenerów wymaga odpowiednio wysokiej skrajni budowli.",
    "Piasecznica zwiększa przyczepność koła do szyny podczas ruszania lub hamowania.",
    "Pofałdowanie powierzchni szyny może powodować charakterystyczny hałas i drgania.",
    "Szybki pociąg w tunelu wytwarza falę ciśnienia, dlatego kształt czoła ma duże znaczenie.",
    "Sprzęg przenosi siły rozciągające i ściskające między wagonami.",
    "Lokomotywy manewrowe są projektowane pod duży uciąg przy małej prędkości.",
    "Rozkład jazdy zawiera rezerwy czasu pomagające odzyskać punktualność po niewielkim opóźnieniu.",
    "Szlifowanie szyn przywraca właściwy profil ich główki i ogranicza wady zmęczeniowe.",
    "Pługi i szczotki torowe chronią zwrotnice przed śniegiem oraz lodem.",
)

SHIP_FACTS: tuple[str, ...] = (
    "Prawo Archimedesa opisuje siłę wyporu równą ciężarowi wypartej cieczy.",
    "Znak wolnej burty, zwany linią Plimsolla, wskazuje bezpieczne zanurzenie statku.",
    "Międzynarodowa konwencja SOLAS została rozwinięta po katastrofie Titanica.",
    "Międzynarodowa Organizacja Morska jest wyspecjalizowaną agencją ONZ.",
    "AIS wymienia dane o pozycji, kursie i tożsamości jednostek.",
    "Lewa burta to port, a prawa to starboard; światła nawigacyjne mają odpowiednio barwy czerwoną i zieloną.",
    "Węzeł oznacza jedną milę morską na godzinę.",
    "Międzynarodowa mila morska ma dokładnie 1852 metry.",
    "TEU jest jednostką odpowiadającą jednemu kontenerowi długości dwudziestu stóp.",
    "Standaryzacja kontenerów skróciła przeładunek między statkiem, koleją i ciężarówką.",
    "Kanał Panamski podnosi i opuszcza statki za pomocą systemu śluz.",
    "Kanał Sueski jest zasadniczo kanałem na poziomie morza i nie potrzebuje śluz tranzytowych.",
    "Gruszka dziobowa może zmniejszyć opór falowy przy projektowej prędkości statku.",
    "Woda balastowa stabilizuje statek, ale może przenosić organizmy między ekosystemami.",
    "Podwójny kadłub ogranicza ryzyko wycieku po uszkodzeniu zewnętrznego poszycia tankowca.",
    "Pędnik azymutalny obraca kierunek ciągu i może zastępować klasyczny ster.",
    "Dynamiczne pozycjonowanie utrzymuje jednostkę w miejscu przy użyciu pędników i czujników.",
    "Radar morski wykrywa obiekty dzięki odbiciu fal radiowych.",
    "Sonar wykorzystuje dźwięk, ponieważ fale radiowe słabo przenikają wodę.",
    "ECDIS łączy elektroniczne mapy nawigacyjne z pozycją i danymi statku.",
    "Rejestrator VDR zapisuje parametry podróży podobnie do rejestratorów lotniczych.",
    "Towarzystwa klasyfikacyjne sprawdzają zgodność konstrukcji statków z regułami technicznymi.",
    "Wolna burta to pionowa odległość między wodnicą a pokładem wolnej burty.",
    "Wysokość metacentryczna jest jednym z podstawowych wskaźników stateczności początkowej.",
    "Zbyt szybkie kołysanie może być równie niebezpieczne dla ładunku jak zbyt mała stateczność.",
    "Kawitacja śruby tworzy pęcherzyki pary, które powodują hałas, drgania i erozję.",
    "Skok śruby określa teoretyczną drogę, jaką przebyłaby ona w jednym obrocie w ośrodku stałym.",
    "Klasyczny ster działa skuteczniej, gdy opływa go strumień wody.",
    "Lodołamacz może wjeżdżać dziobem na lód i kruszyć go ciężarem kadłuba.",
    "Ro-ro przewozi pojazdy wjeżdżające na pokład po rampie.",
    "Zbiornikowce LNG utrzymują gaz ziemny w temperaturze około minus 162 stopni Celsjusza.",
    "Przesunięcie sypkiego ładunku może gwałtownie pogorszyć stateczność masowca.",
    "Zamknięte łodzie ratunkowe chronią rozbitków przed ogniem, falami i pogodą.",
    "Radiopława EPIRB wysyła sygnał alarmowy pomagający zlokalizować jednostkę.",
    "GMDSS łączy satelitarne i radiowe systemy alarmowania na morzu.",
    "Łańcuch kotwiczny układa się w krzywą, która amortyzuje zmiany obciążenia.",
    "Suchy dok pozwala odsłonić podwodną część kadłuba do naprawy i przeglądu.",
    "Porastanie kadłuba zwiększa opór, zużycie paliwa i emisje.",
    "Pilot portowy wnosi lokalną znajomość torów wodnych, prądów i procedur.",
    "Linie ładunkowe uwzględniają różnice warunków sezonowych i obszarów żeglugi.",
)

AIRCRAFT_FACTS: tuple[str, ...] = (
    "Pierwszy udokumentowany lot Flyerem braci Wright w 1903 roku trwał 12 sekund.",
    "Siła nośna wynika z rozkładu ciśnienia i zmiany pędu powietrza wokół skrzydła.",
    "Lotki sterują przechyleniem, ster wysokości pochyleniem, a ster kierunku odchyleniem samolotu.",
    "Klapy zwiększają siłę nośną i opór podczas startu oraz lądowania.",
    "Sloty i skrzela pomagają utrzymać opływ skrzydła przy dużym kącie natarcia.",
    "Przeciągnięcie zależy przede wszystkim od przekroczenia krytycznego kąta natarcia, nie od jednej prędkości.",
    "Rurka Pitota mierzy ciśnienie potrzebne do wyznaczenia prędkości względem powietrza.",
    "Wysokościomierz barometryczny przelicza ciśnienie atmosferyczne na wskazanie wysokości.",
    "Liczba Macha jest stosunkiem prędkości obiektu do lokalnej prędkości dźwięku.",
    "W locie transonicznym na skrzydle mogą powstawać fale uderzeniowe.",
    "Skos skrzydeł opóźnia część niekorzystnych efektów przepływu przy dużych prędkościach.",
    "Silnik odrzutowy wytwarza ciąg, przyspieszając masę powietrza i gazów do tyłu.",
    "Turbofan o dużym stopniu dwuprzepływowości kieruje większość powietrza wokół rdzenia silnika.",
    "Turboprop jest szczególnie sprawny na krótszych trasach i przy umiarkowanych prędkościach.",
    "Pomocnicza jednostka napędowa APU dostarcza energię, gdy główne silniki nie pracują.",
    "Fly-by-wire przekazuje polecenia sterowania sygnałami elektrycznymi do komputerów i siłowników.",
    "Rejestratory lotu są zwykle pomarańczowe, aby łatwiej było je odnaleźć.",
    "FDR zapisuje parametry lotu, a CVR dźwięki i rozmowy w kabinie załogi.",
    "TCAS ostrzega załogi o ryzyku kolizji z innym wyposażonym statkiem powietrznym.",
    "ADS-B nadaje pozycję samolotu wyznaczoną między innymi z nawigacji satelitarnej.",
    "ILS pomaga prowadzić samolot w osi pasa i po ścieżce schodzenia.",
    "VOR wyznacza kierunek względem naziemnej radiolatarni.",
    "RNAV pozwala lecieć po punktach, które nie muszą leżeć bezpośrednio nad radiolatarniami.",
    "Kabina pasażerska jest sprężana, ponieważ na wysokości przelotowej powietrze jest zbyt rozrzedzone.",
    "Maski tlenowe w kabinie spadają po wykryciu znacznego spadku ciśnienia.",
    "Smugi kondensacyjne powstają, gdy para wodna z gazów wylotowych zamarza w zimnym powietrzu.",
    "Winglety mogą ograniczać opór indukowany przez wiry końcowe skrzydła.",
    "Efekt przypowierzchniowy zmniejsza opór indukowany, gdy skrzydło leci blisko ziemi.",
    "Odwracacz ciągu pomaga wyhamować po lądowaniu, lecz nie zastępuje hamulców kół.",
    "Spojlery zmniejszają siłę nośną i zwiększają opór.",
    "Aquaplaning może ograniczyć skuteczność hamowania opon na mokrym pasie.",
    "Odszranianie usuwa lód, który zmienia profil aerodynamiczny skrzydła.",
    "Pokładowy radar pogodowy pomaga wykrywać intensywne opady i komórki burzowe.",
    "Wir śladowy za ciężkim samolotem może być groźny dla lżejszej maszyny.",
    "Przepisy ETOPS określają warunki lotów dwusilnikowych daleko od lotnisk zapasowych.",
    "Concorde rozpoczął regularne przewozy naddźwiękowe w 1976 roku.",
    "Boeing 747 wykonał pierwszy lot w 1969 roku i wszedł do służby pasażerskiej w 1970 roku.",
    "Airbus A380 rozpoczął regularną służbę pasażerską w 2007 roku.",
    "Solar Impulse 2 zakończył etapowe okrążenie świata bez paliwa w 2016 roku.",
    "Szybowiec może zyskiwać wysokość w kominach termicznych bez użycia silnika.",
)

WWII_FACTS: tuple[str, ...] = (
    "Niemcy zaatakowały Polskę 1 września 1939 roku, rozpoczynając wojnę w Europie.",
    "Wielka Brytania i Francja wypowiedziały Niemcom wojnę 3 września 1939 roku.",
    "Związek Radziecki zaatakował Polskę od wschodu 17 września 1939 roku.",
    "Polscy matematycy złamali podstawy szyfru Enigmy jeszcze przed wojną i przekazali wiedzę aliantom.",
    "Bletchley Park było głównym brytyjskim ośrodkiem łamania szyfrów państw Osi.",
    "Nazwa Ultra oznaczała wysoko chronione informacje uzyskiwane z przechwyconych szyfrów.",
    "Bitwa o Anglię w 1940 roku była pierwszą wielką kampanią rozstrzyganą głównie w powietrzu.",
    "Brytyjska sieć radarowa Chain Home pomagała wcześnie wykrywać naloty.",
    "Blitz oznacza serię niemieckich nalotów na brytyjskie miasta w latach 1940–1941.",
    "Operacja Barbarossa rozpoczęła niemiecki atak na Związek Radziecki 22 czerwca 1941 roku.",
    "Japonia zaatakowała Pearl Harbor 7 grudnia 1941 roku.",
    "Stany Zjednoczone wypowiedziały Japonii wojnę 8 grudnia 1941 roku.",
    "Bitwa pod Midway w czerwcu 1942 roku osłabiła japońskie siły lotniskowcowe.",
    "Kapitulacja wojsk Osi pod Stalingradem zakończyła się w lutym 1943 roku.",
    "Druga bitwa pod El Alamein jesienią 1942 roku zatrzymała ofensywę Osi w Egipcie.",
    "Lądowanie w Normandii rozpoczęło się 6 czerwca 1944 roku.",
    "Operacja Overlord była alianckim planem inwazji i działań w Normandii.",
    "Sztuczne porty Mulberry umożliwiały rozładunek zaopatrzenia bez zdobycia dużego portu.",
    "Rurociąg PLUTO dostarczał paliwo przez kanał La Manche po inwazji w Normandii.",
    "Powstanie Warszawskie rozpoczęło się 1 sierpnia 1944 roku i trwało 63 dni.",
    "Dywizjon 303 należał do najskuteczniejszych jednostek myśliwskich podczas bitwy o Anglię.",
    "Polski II Korpus zdobył ruiny klasztoru Monte Cassino w maju 1944 roku.",
    "NKWD zamordowało w 1940 roku tysiące polskich jeńców w ramach zbrodni katyńskiej.",
    "W Holokauście zamordowano około sześciu milionów Żydów.",
    "Armia Czerwona wyzwoliła kompleks Auschwitz-Birkenau 27 stycznia 1945 roku.",
    "Projekt Manhattan doprowadził do skonstruowania pierwszej broni jądrowej.",
    "Bomby atomowe zrzucono na Hiroszimę 6 sierpnia i Nagasaki 9 sierpnia 1945 roku.",
    "Japonia ogłosiła przyjęcie warunków kapitulacji 15 sierpnia 1945 roku.",
    "Formalny akt kapitulacji Japonii podpisano 2 września 1945 roku na pokładzie USS Missouri.",
    "Bezwarunkowa kapitulacja Niemiec weszła w życie 8 maja 1945 roku.",
    "Organizacja Narodów Zjednoczonych została utworzona w 1945 roku.",
    "Konwoje atlantyckie grupowały statki handlowe pod osłoną okrętów eskorty.",
    "Statki typu Liberty budowano masowo, aby uzupełniać straty alianckiego transportu.",
    "Masowa produkcja penicyliny podczas wojny zwiększyła możliwości leczenia zakażeń.",
    "V-1 był bezzałogowym pociskiem manewrującym, a V-2 pierwszym użytym bojowo pociskiem balistycznym dalekiego zasięgu.",
    "Messerschmitt Me 262 był pierwszym odrzutowym myśliwcem użytym operacyjnie.",
    "Radziecki T-34 łączył pochyły pancerz, szerokie gąsienice i względnie prostą produkcję.",
    "Navajo Code Talkers przekazywali zaszyfrowane wiadomości na Pacyfiku.",
    "Operacja Mincemeat wykorzystała fałszywe dokumenty, aby zmylić Niemców przed inwazją na Sycylię.",
    "System Double Cross wykorzystywał przejętych agentów do przekazywania Niemcom dezinformacji.",
)

PIRATE_FACTS: tuple[str, ...] = (
    "Za złoty wiek piractwa atlantyckiego uznaje się zwykle okres od połowy XVII do początku XVIII wieku.",
    "Kaper działał z upoważnienia państwa, a pirat bez legalnej komisji.",
    "List kaperski pozwalał prywatnemu statkowi atakować jednostki wskazanego przeciwnika w czasie wojny.",
    "Nie istniał jeden wzór Jolly Rogera; pirackie załogi używały wielu różnych flag.",
    "Czarna flaga często miała skłonić statek do poddania się bez walki.",
    "Artykuły okrętowe określały podział łupów, obowiązki i kary na części pirackich statków.",
    "Niektóre pirackie załogi wypłacały ustalone odszkodowania za utratę kończyny lub oka.",
    "Na części statków kapitan był wybierany i mógł zostać odwołany przez załogę.",
    "Kwatermistrz mógł kontrolować zapasy i reprezentować interesy załogi wobec kapitana.",
    "Blackbeard nazywał się Edward Teach lub Thatch i zginął w 1718 roku.",
    "Anne Bonny i Mary Read służyły w załodze Calico Jacka schwytanej w 1720 roku.",
    "Bartholomew Roberts zdobył setki jednostek w krótkiej karierze zakończonej w 1722 roku.",
    "Henry Every zdobył w 1695 roku bogato załadowany statek Ganj-i-Sawai.",
    "William Kidd rozpoczął wyprawę jako kaper, a w 1701 roku został stracony za piractwo.",
    "Port Royal na Jamajce był ważnym ośrodkiem korsarzy przed trzęsieniem ziemi w 1692 roku.",
    "Nassau na Bahamach stało się na początku XVIII wieku bazą wielu pirackich załóg.",
    "Woodes Rogers objął urząd gubernatora Bahamów w 1718 roku i zwalczał piracką republikę w Nassau.",
    "Hiszpańskie floty skarbowe przewoziły przez Atlantyk srebro i inne towary z Ameryk.",
    "Piraci często woleli zastraszyć ofiarę, ponieważ walka mogła zniszczyć statek i ładunek.",
    "Abordaż pozwalał przejąć statek i towary bez zatapiania zdobyczy.",
    "Kilienowanie kadłuba usuwało porosty przez przechylenie statku na bok przy brzegu.",
    "Świdrak okrętowy niszczył drewniane kadłuby, drążąc w nich tunele.",
    "Slupy były cenione przez piratów za szybkość, zwrotność i niewielkie zanurzenie.",
    "Zdobyty statek mógł zostać przebudowany i przemianowany przez nową załogę.",
    "Mapy z przerywaną linią i znakiem X są przede wszystkim późniejszym motywem literackim.",
    "Chodzenie po desce nie było typową, dobrze udokumentowaną karą złotego wieku piractwa.",
    "Papugi trafiały do Europy jako egzotyczny towar, ale ich związek z piratami utrwaliła literatura.",
    "Słowo buccaneer wywodzi się od karaibskich myśliwych suszących mięso na rusztach boucan.",
    "Korsarze działali także na Morzu Śródziemnym, nie tylko na Atlantyku.",
    "Korsarze berberyjscy operowali z portów Afryki Północnej i polowali na statki oraz jeńców.",
    "Zheng Yi Sao dowodziła na początku XIX wieku potężną chińską konfederacją piracką.",
    "Chińska Flota Czerwonej Flagi składała się z setek dżonek podzielonych na eskadry.",
    "Współczesne piractwo występuje między innymi w Zatoce Gwinejskiej i części Azji Południowo-Wschodniej.",
    "Prawo morza odróżnia piractwo na morzu pełnym od napadu zbrojnego na wodach terytorialnych.",
    "Piractwo jest jednym z przestępstw, wobec których państwa mogą stosować jurysdykcję uniwersalną.",
    "Współcześni piraci częściej żądają okupu niż poszukują skrzyń ze złotem.",
    "Cytadela okrętowa jest zabezpieczonym pomieszczeniem, w którym załoga może przeczekać napad.",
    "Patrole międzynarodowe i uzbrojona ochrona ograniczyły liczbę skutecznych porwań u wybrzeży Somalii.",
    "Deklaracja paryska z 1856 roku zniosła korsarstwo między państwami, które ją podpisały.",
    "William Kidd zakopał część łupu na Gardiners Island, lecz władze szybko go odnalazły.",
)

ALL_FACTS: tuple[str, ...] = TRAIN_FACTS + SHIP_FACTS + AIRCRAFT_FACTS + WWII_FACTS + PIRATE_FACTS

if len(ALL_FACTS) != 200 or len(set(ALL_FACTS)) != 200:
    raise RuntimeError("Talia ciekawostek musi zawierać dokładnie 200 unikalnych pozycji.")
